version: "3.9"

services:
  sql_to_pg:
    build: ./sqlite_to_postgres
    env_file:
      - ./sqlite_to_postgres/prod.env
    networks:
      - movies_app

networks:
  movies_app:
      name: movies_app
      external: true
        