version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
      - POSTGRES_DB=movies_database
    ports:
      - 5432:5432
    networks:
      - movies_app

  swagger:
    image: swaggerapi/swagger-ui 
    restart: always 
    volumes:
      - ./openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    ports:
      - 8080:8080
    networks:
      - movies_app
    

networks:
  movies_app:


volumes:
  postgres_data:
