version: '3.9'
services:
  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - movies_app

  etl:
    build: .
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./state.json:/etl/state.json
    networks:
      - movies_app

networks:
  movies_app:
    name: movies_app

