version: '3.9'
services:
  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123qwe
      - ELASTIC_USERNAME=elastic
    networks:
      - movies_app
    ports:
      - 9200:9200
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    
  etl:
    build: .
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./state.json:/etl/state.json
    networks:
      - movies_app

networks:
  movies_app:
    name: movies_app

volumes:
  elastic_volume: