version: '3.9'
services:
  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://127.0.0.1:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    ports:
      - 9200:9200

  etl:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./etl_state:/etl/etl_state:rw
    depends_on:
      elastic_search:
        condition: service_healthy
    network_mode: host



volumes:
  etl_state:
  elastic_volume:

